//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitRefresh.Schedule {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScheduleMasterString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleMasterString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitRefresh.Schedule.ScheduleMasterString", typeof(ScheduleMasterString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 一二节 的本地化字符串。
        /// </summary>
        internal static string 一二节 {
            get {
                return ResourceManager.GetString("一二节", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 七八节 的本地化字符串。
        /// </summary>
        internal static string 七八节 {
            get {
                return ResourceManager.GetString("七八节", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三四节 的本地化字符串。
        /// </summary>
        internal static string 三四节 {
            get {
                return ResourceManager.GetString("三四节", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中午 的本地化字符串。
        /// </summary>
        internal static string 中午 {
            get {
                return ResourceManager.GetString("中午", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五六节 的本地化字符串。
        /// </summary>
        internal static string 五六节 {
            get {
                return ResourceManager.GetString("五六节", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点待定 的本地化字符串。
        /// </summary>
        internal static string 地点待定 {
            get {
                return ResourceManager.GetString("地点待定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您在{0}有一节{1}即将开始。 的本地化字符串。
        /// </summary>
        internal static string 您在_0_有一节_1_即将开始 {
            get {
                return ResourceManager.GetString("您在{0}有一节{1}即将开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚上 的本地化字符串。
        /// </summary>
        internal static string 晚上 {
            get {
                return ResourceManager.GetString("晚上", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课表格式错误。 的本地化字符串。
        /// </summary>
        internal static string 课表格式错误 {
            get {
                return ResourceManager.GetString("课表格式错误", resourceCulture);
            }
        }
    }
}
