name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build project
        run: dotnet build -c release Schedule.sln
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Schedule/Schedule.csproj 
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: HitRefresh.Schedule
