name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101
      - name: build project
        run: dotnet build -c release Schedule.sln
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Schedule/Schedule.csproj 
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: HitRefresh.Schedule
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-publish
          path: ./src/bin/Release/